<?php
require_once __DIR__ . '/../../core/api_pairing.php';
pairing_auth('readonly');
$today=date('Y-m-d');$month=trim((string)($_GET['month']??date('Y-m')));if(!preg_match('/^\d{4}-\d{2}$/',$month))$month=date('Y-m');$start=$month.'-01';$end=date('Y-m-d',strtotime($start.' +1 month'));
$name=(string)setting('company_name','Dapur Adena');
$data=['system'=>['type'=>'dapur','name'=>$name],'system_name'=>$name,'finished_products'=>0,'active_finished_products'=>0,'raw_materials'=>0,'pending_pairing'=>pairing_pending_count(),'productions_today'=>0,'production_qty_today'=>0.0,'production_batches_month'=>0,'production_qty_month'=>0.0,'pending_distributions'=>0,'distribution'=>['draft'=>0,'posted'=>0,'sent'=>0,'received'=>0,'failed'=>0,'cancelled'=>0,'total'=>0],'employees_count'=>0,'dapur_omset_month'=>0.0,'omset_dapur_bulan_ini'=>0.0,'kitchen_revenue_month'=>0.0,'kitchen_revenue_branches'=>[],'kpi'=>['total_points'=>0.0,'average_points'=>0.0,'employee_with_activity'=>0,'top_employee'=>null],'finance'=>['purchase_total'=>0.0,'expense_total'=>0.0,'payment_pending'=>0.0]];
try{$data['finished_products']=(int)db()->query('SELECT COUNT(*) FROM finished_products')->fetchColumn();}catch(Throwable $e){}
try{$data['active_finished_products']=(int)db()->query('SELECT COUNT(*) FROM finished_products WHERE is_active=1')->fetchColumn();}catch(Throwable $e){}
try{$data['raw_materials']=(int)db()->query('SELECT COUNT(*) FROM raw_materials WHERE is_active=1')->fetchColumn();}catch(Throwable $e){}
try{$st=db()->prepare("SELECT COUNT(*) c,COALESCE(SUM(qty_produced),0) q FROM production_headers WHERE production_date=? AND status<>'cancelled'");$st->execute([$today]);$r=$st->fetch(PDO::FETCH_ASSOC)?:[];$data['productions_today']=(int)($r['c']??0);$data['production_qty_today']=(float)($r['q']??0);}catch(Throwable $e){}
try{$st=db()->prepare("SELECT COUNT(*) c,COALESCE(SUM(qty_produced),0) q FROM production_headers WHERE production_date>=? AND production_date<? AND status<>'cancelled'");$st->execute([$start,$end]);$r=$st->fetch(PDO::FETCH_ASSOC)?:[];$data['production_batches_month']=(int)($r['c']??0);$data['production_qty_month']=(float)($r['q']??0);}catch(Throwable $e){}
try{$rows=db()->query("SELECT status,COUNT(*) c FROM kitchen_sales_headers GROUP BY status")->fetchAll(PDO::FETCH_ASSOC)?:[];foreach($rows as $r){$s=(string)$r['status'];$c=(int)$r['c'];$data['distribution']['total']+=$c;if($s==='draft')$data['distribution']['draft']+=$c;elseif($s==='posted')$data['distribution']['posted']+=$c;elseif($s==='sent_to_store')$data['distribution']['sent']+=$c;elseif($s==='received_by_store')$data['distribution']['received']+=$c;elseif($s==='failed_sync')$data['distribution']['failed']+=$c;elseif($s==='cancelled')$data['distribution']['cancelled']+=$c;}$data['pending_distributions']=$data['distribution']['sent'];}catch(Throwable $e){}
try{$data['employees_count']=(int)db()->query("SELECT COUNT(*) FROM employees WHERE is_active=1 AND LOWER(COALESCE(role_key,'pegawai_dapur'))<>'owner'")->fetchColumn();}catch(Throwable $e){}
try{$st=db()->prepare("SELECT COALESCE(SUM(total_amount),0) FROM kitchen_sales_headers WHERE sale_date>=? AND sale_date<? AND status<>'cancelled'");$st->execute([$start,$end]);$rev=(float)$st->fetchColumn();$data['dapur_omset_month']=$rev;$data['omset_dapur_bulan_ini']=$rev;$data['kitchen_revenue_month']=$rev;}catch(Throwable $e){}
try{$st=db()->prepare("SELECT COALESCE(s.store_name,'Tanpa Toko') store_name,COALESCE(SUM(h.total_amount),0) total_amount FROM kitchen_sales_headers h LEFT JOIN stores s ON s.id=h.store_id WHERE h.sale_date>=? AND h.sale_date<? AND h.status<>'cancelled' GROUP BY h.store_id,s.store_name ORDER BY total_amount DESC");$st->execute([$start,$end]);foreach($st->fetchAll(PDO::FETCH_ASSOC) as $r)$data['kitchen_revenue_branches'][]=['name'=>(string)$r['store_name'],'store_name'=>(string)$r['store_name'],'kitchen_revenue_month'=>(float)$r['total_amount'],'internal_transfer'=>true];}catch(Throwable $e){}
try{$st=db()->prepare("SELECT e.id,e.employee_name,COALESCE(SUM(ea.total_points),0) pts,COUNT(ea.id) acts FROM employees e LEFT JOIN employee_activities ea ON ea.employee_id=e.id AND ea.activity_date>=? AND ea.activity_date<? WHERE e.is_active=1 AND LOWER(COALESCE(e.role_key,'pegawai_dapur'))<>'owner' GROUP BY e.id,e.employee_name ORDER BY pts DESC");$st->execute([$start,$end]);$rows=$st->fetchAll(PDO::FETCH_ASSOC)?:[];$total=0;$active=0;foreach($rows as $r){$total+=(float)$r['pts'];if((int)$r['acts']>0)$active++;}$data['kpi']['total_points']=$total;$data['kpi']['employee_with_activity']=$active;$data['kpi']['average_points']=count($rows)>0?$total/count($rows):0;if($rows)$data['kpi']['top_employee']=['employee_id'=>(string)$rows[0]['id'],'name'=>$rows[0]['employee_name'],'total_points'=>(float)$rows[0]['pts']];}catch(Throwable $e){}
try{if(table_exists('purchase_headers')){$st=db()->prepare("SELECT COALESCE(SUM(total_amount),0) FROM purchase_headers WHERE purchase_date>=? AND purchase_date<? AND status='posted'");$st->execute([$start,$end]);$data['finance']['purchase_total']=(float)$st->fetchColumn();}}catch(Throwable $e){}
try{if(table_exists('expenses')){$st=db()->prepare("SELECT COALESCE(SUM(amount),0) FROM expenses WHERE expense_date>=? AND expense_date<? AND status IN ('approved','paid') AND deleted_at IS NULL");$st->execute([$start,$end]);$data['finance']['expense_total']=(float)$st->fetchColumn();}}catch(Throwable $e){}
try{if(table_exists('payment_requests')){$st=db()->prepare("SELECT COALESCE(SUM(amount),0) FROM payment_requests WHERE request_date>=? AND request_date<? AND status IN ('draft','submitted','approved') AND deleted_at IS NULL");$st->execute([$start,$end]);$data['finance']['payment_pending']=(float)$st->fetchColumn();}}catch(Throwable $e){}
$data['purchase_total_month']=$data['finance']['purchase_total'];$data['expense_total_month']=$data['finance']['expense_total'];
pairing_ok(['data'=>$data]);
