<?php
require_once __DIR__ . '/../../core/api_pairing.php';
pairing_auth('financial.read');
$month=trim((string)($_GET['month']??date('Y-m')));if(!preg_match('/^\d{4}-\d{2}$/',$month))$month=date('Y-m');$start=$month.'-01';$end=date('Y-m-d',strtotime($start.' +1 month'));$include=(int)($_GET['include_rows']??1)===1;
$data=['month'=>$month,'system'=>['type'=>'dapur','name'=>(string)setting('company_name','Dapur Adena')],'purchase_total'=>0.0,'expense_total'=>0.0,'payment_request_pending'=>0.0,'payment_request_paid'=>0.0,'internal_distribution_value'=>0.0,'purchases'=>[],'expenses'=>[],'payment_requests'=>[]];
try{
 if(table_exists('purchase_headers')){$st=db()->prepare("SELECT * FROM purchase_headers WHERE purchase_date>=? AND purchase_date<? AND status<>'cancelled' ORDER BY id DESC");$st->execute([$start,$end]);foreach($st->fetchAll(PDO::FETCH_ASSOC) as $r){if(($r['status']??'')==='posted')$data['purchase_total']+=(float)$r['total_amount'];if($include)$data['purchases'][]=['external_id'=>(string)$r['id'],'transaction_no'=>$r['purchase_no'],'date'=>$r['purchase_date'],'supplier'=>$r['supplier_name'],'status'=>$r['status'],'amount'=>(float)$r['total_amount'],'is_internal'=>false];}}
 if(table_exists('expenses')){$st=db()->prepare("SELECT * FROM expenses WHERE expense_date>=? AND expense_date<? AND status IN ('approved','paid') AND deleted_at IS NULL ORDER BY id DESC");$st->execute([$start,$end]);foreach($st->fetchAll(PDO::FETCH_ASSOC) as $r){$data['expense_total']+=(float)$r['amount'];if($include)$data['expenses'][]=['external_id'=>(string)$r['id'],'record_uuid'=>$r['record_uuid'],'transaction_no'=>$r['expense_no'],'date'=>$r['expense_date'],'category'=>$r['category_name_snapshot'],'description'=>$r['title'],'status'=>$r['status'],'amount'=>(float)$r['amount'],'vendor'=>$r['vendor_name']];}}
 if(table_exists('payment_requests')){$st=db()->prepare("SELECT * FROM payment_requests WHERE request_date>=? AND request_date<? AND deleted_at IS NULL ORDER BY id DESC");$st->execute([$start,$end]);foreach($st->fetchAll(PDO::FETCH_ASSOC) as $r){if(in_array($r['status'],['draft','submitted','approved'],true))$data['payment_request_pending']+=(float)$r['amount'];if($r['status']==='paid')$data['payment_request_paid']+=(float)$r['amount'];if($include)$data['payment_requests'][]=['external_id'=>(string)$r['id'],'record_uuid'=>$r['record_uuid'],'transaction_no'=>$r['request_no'],'date'=>$r['request_date'],'due_date'=>$r['due_date'],'category'=>$r['category_name_snapshot'],'description'=>$r['title'],'status'=>$r['status'],'amount'=>(float)$r['amount'],'vendor'=>$r['vendor_name']];}}
 if(table_exists('kitchen_sales_headers')){$st=db()->prepare("SELECT COALESCE(SUM(total_amount),0) FROM kitchen_sales_headers WHERE sale_date>=? AND sale_date<? AND status<>'cancelled'");$st->execute([$start,$end]);$data['internal_distribution_value']=(float)$st->fetchColumn();}
}catch(Throwable $e){pairing_err('Gagal membaca ringkasan keuangan dapur: '.$e->getMessage(),500);}
pairing_ok(['data'=>$data]);
