'use strict';
const state={cart:[],customer:null}; const rp=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0)); const uid=()=>crypto.randomUUID();
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
async function init(){const s=await window.pos.session();if(s.logged_in){showApp(s.user);await renderProducts();}else{$('#login').classList.remove('hidden')} window.pos.onSync(renderSyncEvent);}
function showApp(user){$('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#userName').textContent=user?.name||user?.username||'';loadAbout();}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='Menghubungkan...';const r=await window.pos.login($('#username').value,$('#password').value);if(!r.ok){$('#loginError').textContent=r.error;return;}showApp(r.user);await renderProducts();});
$$('.nav').forEach(b=>b.onclick=async()=>{const p=b.dataset.page;$$('.nav').forEach(x=>x.classList.toggle('active',x===b));$$('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+p));if(p==='riwayat')renderSales();if(p==='sinkron')renderSyncInfo();});
async function renderProducts(){const rows=await window.pos.products($('#productSearch').value||'');$('#products').innerHTML=rows.map(p=>`<button class="product" data-id="${p.id}"><div class="name">${esc(p.name)}</div><div class="meta">${esc(p.category||'Tanpa kategori')} · ${esc(p.unit||'pcs')}</div><div class="price">${rp(p.sale_price)}</div><div class="stock">Stok lokal: ${num(p.stock_qty)}</div></button>`).join('')||'<p>Belum ada data produk lokal. Jalankan sinkronisasi.</p>'; $$('.product').forEach(b=>b.onclick=()=>addProduct(rows.find(p=>p.id===Number(b.dataset.id))));}
$('#productSearch').addEventListener('input',()=>renderProducts());$('#refreshProducts').onclick=renderProducts;
function addProduct(p){const ex=state.cart.find(x=>x.product_id===p.id);if(ex)ex.qty+=1;else state.cart.push({product_id:p.id,item_name:p.name,unit:p.unit,qty:1,original_price:Number(p.sale_price),discount_type:'none',discount_value:0,stock_qty:Number(p.stock_qty)});renderCart();}
function calcLine(i){const gross=i.qty*i.original_price;let disc=0;if(i.discount_type==='percent')disc=gross*Math.min(100,Math.max(0,i.discount_value))/100;else if(i.discount_type==='nominal')disc=Math.min(gross,Math.max(0,i.discount_value));return{gross,discount_amount:disc,subtotal:gross-disc};}
function totals(){return state.cart.reduce((a,i)=>{const l=calcLine(i);a.gross+=l.gross;a.discount+=l.discount_amount;a.total+=l.subtotal;return a;},{gross:0,discount:0,total:0});}
function renderCart(){const c=$('#cartItems');c.innerHTML=state.cart.map((i,n)=>`<div class="cart-row" data-n="${n}"><div class="cart-top"><strong>${esc(i.item_name)}</strong><span>${rp(calcLine(i).subtotal)}</span></div><div class="cart-controls"><input class="qty" type="number" min="0.0001" step="1" value="${i.qty}"><select class="dtype"><option value="none" ${i.discount_type==='none'?'selected':''}>No disc</option><option value="percent" ${i.discount_type==='percent'?'selected':''}>Disc %</option><option value="nominal" ${i.discount_type==='nominal'?'selected':''}>Disc Rp</option></select><input class="dval" type="number" min="0" value="${i.discount_value}"><button class="remove">×</button></div></div>`).join('')||'<p style="color:#777">Keranjang masih kosong.</p>'; $$('.cart-row').forEach(r=>{const i=state.cart[Number(r.dataset.n)];r.querySelector('.qty').onchange=e=>{i.qty=Math.max(.0001,Number(e.target.value)||1);renderCart()};r.querySelector('.dtype').onchange=e=>{i.discount_type=e.target.value;renderCart()};r.querySelector('.dval').onchange=e=>{i.discount_value=Math.max(0,Number(e.target.value)||0);renderCart()};r.querySelector('.remove').onclick=()=>{state.cart.splice(Number(r.dataset.n),1);renderCart()};});const t=totals();$('#gross').textContent=rp(t.gross);$('#discount').textContent=rp(t.discount);$('#total').textContent=rp(t.total);calcChange();}
$('#customerSearch').addEventListener('input',async e=>{const q=e.target.value.trim();if(q.length<2){$('#customerResults').innerHTML='';return;}const rows=await window.pos.customers(q);$('#customerResults').innerHTML=rows.map(c=>`<div class="customer-result" data-id="${c.id}">${esc(c.customer_name)}${c.phone?' · '+esc(c.phone):''}</div>`).join(''); $$('.customer-result').forEach(el=>el.onclick=()=>{state.customer=rows.find(c=>c.id===Number(el.dataset.id));$('#selectedCustomer').textContent='Dipilih: '+state.customer.customer_name;$('#customerSearch').value='';$('#customerResults').innerHTML='';});});
$('#paymentMethod').onchange=()=>{$('#paidWrap').style.display=$('#paymentMethod').value==='cash'?'grid':'none';calcChange()};$('#paidAmount').oninput=calcChange;function calcChange(){const t=totals().total,p=$('#paymentMethod').value==='cash'?Number($('#paidAmount').value||0):t;$('#change').textContent=rp(Math.max(0,p-t));}
$('#pay').onclick=async()=>{if(!state.cart.length)return alert('Keranjang kosong.');const t=totals();const method=$('#paymentMethod').value;const paid=method==='cash'?Number($('#paidAmount').value||0):t;if(method==='cash'&&paid<t)return alert('Uang diterima kurang dari total.');for(const i of state.cart){if(i.qty>i.stock_qty && !confirm(`Stok lokal ${i.item_name} hanya ${num(i.stock_qty)}. Tetap lanjut?`))return;}const now=new Date(),uuid=uid();const sale={uuid,local_no:'POS-'+compactDate(now)+'-'+uuid.slice(0,6).toUpperCase(),sale_date:localDate(now),customer_id:state.customer?.id||null,customer_name:state.customer?.customer_name||null,gross_amount:t.gross,discount_amount:t.discount,total_amount:t.total,payment_method:method,paid_amount:paid,change_amount:Math.max(0,paid-t.total),notes:$('#notes').value.trim()||null,created_at:now.toISOString(),items:state.cart.map(i=>({...i,...calcLine(i)}))};const r=await window.pos.createSale(sale);if(!r.ok)return alert(r.error);state.cart=[];state.customer=null;$('#selectedCustomer').textContent='';$('#paidAmount').value=0;$('#notes').value='';renderCart();await renderProducts();if(confirm('Transaksi tersimpan. Cetak struk?'))await window.pos.printReceipt(uuid);};
async function renderSales(){const rows=await window.pos.sales();$('#salesList').innerHTML=rows.map(s=>`<div class="sale"><div><strong>${esc(s.server_sale_no||s.local_no)}</strong><br><small>${esc(s.created_at)}</small></div><div>${esc(s.customer_name||'Customer langsung')}</div><div><strong>${rp(s.total_amount)}</strong><br><small>${esc(s.payment_method)}</small></div><div><span class="badge ${s.status}">${esc(s.status)}</span> <button data-print="${s.uuid}">Print</button></div></div>`).join('')||'<p>Belum ada transaksi.</p>'; $$('[data-print]').forEach(b=>b.onclick=()=>window.pos.printReceipt(b.dataset.print));}
$('#reloadSales').onclick=renderSales;$('#syncNow').onclick=async()=>{$('#syncResult').textContent='Sinkronisasi...';const r=await window.pos.sync();$('#syncResult').textContent=r.ok?`Selesai. ${r.pushed} transaksi terkirim, ${r.failed} gagal.`:`Gagal: ${r.error}`;await renderSyncInfo();await renderProducts();};async function renderSyncInfo(){const x=await window.pos.syncInfo();$('#syncInfo').innerHTML=`<div>Pending transaksi: <strong>${x.pending}</strong></div><div>Sinkron terakhir: <strong>${x.last_sync||'Belum pernah'}</strong></div><div>Master data terakhir: <strong>${x.last_master_sync||'Belum pernah'}</strong></div>`;}function renderSyncEvent(d){$('#conn').textContent=d.online?'● Online · tersinkron':'● Offline-ready';$('#conn').style.color=d.online?'#245d35':'#8b6b20';}
async function loadAbout(){const a=await window.pos.about();$('#about').innerHTML=`<p>Versi: <strong>${esc(a.version)}</strong></p><p>Device ID: <code>${esc(a.device_id)}</code></p>`;}$('#logout').onclick=async()=>{if(!confirm('Keluar dari akun di perangkat ini?'))return;await window.pos.logout();location.reload();};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}function num(n){return Number(n||0).toLocaleString('id-ID',{maximumFractionDigits:4});}function pad(n){return String(n).padStart(2,'0')}function localDate(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}function compactDate(d){return `${String(d.getFullYear()).slice(2)}${pad(d.getMonth()+1)}${pad(d.getDate())}${pad(d.getHours())}${pad(d.getMinutes())}`}
renderCart();init();
