<?php
require_once __DIR__ . '/../core/db.php';
require_once __DIR__ . '/../core/helpers.php';
require_once __DIR__ . '/../core/auth.php';
require_once __DIR__ . '/../core/api_pairing.php';
require_login(); ensure_api_pairing_schema();
$u=current_user(); $customCss=''; $pending=pairing_pending_count(); $notes=pairing_latest_notifications();
$msg=$_GET['msg']??''; $hiddenStatuses="'revoked','deleted','cancelled','canceled','rejected','inactive'";
$incoming=db()->query("SELECT * FROM api_pairing_requests WHERE direction='incoming' AND status='pending' ORDER BY id DESC LIMIT 50")->fetchAll(PDO::FETCH_ASSOC);
$outgoing=db()->query("SELECT * FROM api_pairing_requests WHERE direction='outgoing' AND LOWER(TRIM(COALESCE(status,''))) NOT IN ($hiddenStatuses) ORDER BY id DESC LIMIT 50")->fetchAll(PDO::FETCH_ASSOC);
$conns=db()->query("SELECT * FROM api_connections WHERE LOWER(TRIM(COALESCE(status,''))) NOT IN ($hiddenStatuses) ORDER BY id DESC LIMIT 50")->fetchAll(PDO::FETCH_ASSOC);
function status_badge($s){ $c=$s==='approved'||$s==='active'||$s==='ok'?'ok':($s==='pending'?'warn':'danger'); return '<span class="badge '.$c.'">'.e((string)$s).'</span>'; }
function legacy_api_type_key(array $c): string {
  $raw=strtolower(trim((string)(($c['remote_system_type']??'').' '.($c['connection_type']??'').' '.($c['connection_name']??''))));
  if(preg_match('/\b(hope|hp|hope_pos|pos)\b/',$raw) || str_contains($raw,'hope')) return 'hope';
  if(str_contains($raw,'backoffice') || str_contains($raw,'back office') || preg_match('/\bbo\b/',$raw)) return 'backoffice';
  if(str_contains($raw,'adena_store') || str_contains($raw,'store') || str_contains($raw,'toko') || str_contains($raw,'cabang')) return 'store';
  if(str_contains($raw,'dapur')) return 'dapur';
  return trim((string)($c['remote_system_type']??'')) ?: 'external';
}
function legacy_api_action_form(int $id,string $act,string $label,string $returnPage='api_integrations',string $class='btn btn-light',string $confirm=''): string {
  $ons=$confirm!==''?' onsubmit="return confirm(&quot;'.e($confirm).'&quot;)"':'';
  return '<form method="post" action="api_pairing_action.php" style="display:inline"'.$ons.'><input type="hidden" name="csrf" value="'.e(csrf_token()).'"><input type="hidden" name="return_page" value="'.e($returnPage).'"><input type="hidden" name="act" value="'.e($act).'"><input type="hidden" name="id" value="'.$id.'"><button class="'.e($class).'">'.e($label).'</button></form>';
}
function legacy_api_test_buttons(array $c): string {
  $cid=(int)($c['id']??0); $type=legacy_api_type_key($c); $html=legacy_api_action_form($cid,'test_connection','Test Ping');
  if($type==='hope'){ $html.=legacy_api_action_form($cid,'test_hope_products','Test Produk').legacy_api_action_form($cid,'test_hope_transfer','Test Transfer Stok').legacy_api_action_form($cid,'refresh_scope','Refresh Scope'); }
  elseif($type==='backoffice'){ $html.=legacy_api_action_form($cid,'test_backoffice_health','Test Health').legacy_api_action_form($cid,'test_backoffice_dashboard','Test Dashboard').legacy_api_action_form($cid,'test_backoffice_kpi','Test KPI Dapur').legacy_api_action_form($cid,'test_backoffice_employees','Test Employees').legacy_api_action_form($cid,'refresh_scope','Refresh Scope'); }
  else { $html.=legacy_api_action_form($cid,'refresh_scope','Refresh Scope'); }
  return $html.legacy_api_action_form($cid,'revoke_connection','Hapus/Revoke','api_integrations','btn btn-danger','Cabut koneksi ini?');
}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pairing Koneksi</title><link rel="stylesheet" href="../assets/app.css"><style><?php echo $customCss; ?>.topbar{justify-content:space-between}.topbar-right{margin-left:auto;display:flex;gap:8px;align-items:center}.notif{position:relative}.notif-btn{border:1px solid #dbeafe;background:#fff;border-radius:999px;padding:8px 12px;cursor:pointer}.notif-badge{background:#ef4444;color:#fff;border-radius:999px;font-size:11px;padding:2px 6px;margin-left:4px}.notif-menu{display:none;position:absolute;right:0;top:42px;width:340px;max-width:88vw;background:#fff;border:1px solid #e5e7eb;border-radius:14px;box-shadow:0 20px 45px rgba(15,23,42,.16);z-index:20}.notif:hover .notif-menu{display:block}.notif-item{padding:10px 12px;border-bottom:1px solid #f1f5f9}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:16px}@media(max-width:760px){.grid2{grid-template-columns:1fr}.desktop-compact{font-size:15px}.btn,input,select{min-height:42px}.table{font-size:14px}}</style></head>
<body class="desktop-compact"><div class="container"><aside class="sidebar"><div class="sb-top"><strong>Dapur</strong></div><nav class="nav"><a href="index.php">Dashboard</a><a class="active" href="api_pairing.php">Pairing Koneksi</a></nav></aside><div class="main"><div class="topbar"><button class="btn" data-toggle-sidebar type="button">Menu</button><strong>Pairing Koneksi API</strong><div class="topbar-right"><div class="notif"><button class="notif-btn" type="button">🔔 <?php if($pending): ?><span class="notif-badge"><?php echo (int)$pending; ?></span><?php endif; ?></button><div class="notif-menu"><div class="notif-item"><strong>Notifikasi Pairing</strong></div><?php foreach($notes as $n): ?><div class="notif-item"><div><strong><?php echo e($n['requester_name']); ?></strong></div><small><?php echo e($n['requester_type'].' · '.$n['status'].' · '.$n['created_at']); ?></small></div><?php endforeach; if(!$notes): ?><div class="notif-item muted">Belum ada notifikasi.</div><?php endif; ?></div></div></div></div><div class="content">
<?php if($msg): ?><div class="card" style="border-color:#bfdbfe;background:#eff6ff"><?php echo e($msg); ?></div><?php endif; ?>
<div class="grid2"><div class="card"><h3>Request Pairing Keluar</h3><p class="muted">Isi HTTPS tujuan dan jenis sistem. Token dibuat otomatis setelah tujuan approve.</p><form method="post" action="api_pairing_action.php"><input type="hidden" name="csrf" value="<?php echo e(csrf_token()); ?>"><input type="hidden" name="act" value="create_request"><label>Nama Koneksi<input name="connection_name" placeholder="Adena Pangkal Pinang / Dapur" required></label><label>URL Tujuan<input name="base_url" placeholder="https://domain-tujuan.com" required></label><label>Jenis Tujuan<select name="target_type"><option value="hope">HOPe/HP</option><option value="adena_store">Toko Adena</option><option value="dapur">Dapur</option><option value="backoffice">Back Office</option></select></label><button class="btn">Kirim Request Pairing</button></form></div><div class="card"><h3>Aturan Scope</h3><ul><li>POS Desktop: tidak diubah.</li><li>API web lain: tetap semula, read-only.</li><li>Antar toko: read-only produk/kategori/gambar.</li><li>Dapur: bisa kirim stok/produk ke toko.</li><li>Back Office: admin operasional read/write.</li></ul></div></div>
<div class="card"><h3>Request Masuk</h3><table class="table"><tr><th>Waktu</th><th>Peminta</th><th>Jenis</th><th>URL</th><th>Scope</th><th>Status</th><th>Aksi</th></tr><?php foreach($incoming as $r): ?><tr><td><?php echo e($r['created_at']); ?></td><td><?php echo e($r['requester_name']); ?></td><td><?php echo e($r['requester_type']); ?></td><td><?php echo e($r['requester_base_url']); ?></td><td><?php echo e($r['requested_scope']); ?></td><td><?php echo status_badge($r['status']); ?></td><td><?php if($r['status']==='pending'): ?><form method="post" action="api_pairing_action.php" style="display:inline"><input type="hidden" name="csrf" value="<?php echo e(csrf_token()); ?>"><input type="hidden" name="act" value="approve"><input type="hidden" name="id" value="<?php echo (int)$r['id']; ?>"><button class="btn">Approve</button></form> <form method="post" action="api_pairing_action.php" style="display:inline"><input type="hidden" name="csrf" value="<?php echo e(csrf_token()); ?>"><input type="hidden" name="act" value="reject"><input type="hidden" name="id" value="<?php echo (int)$r['id']; ?>"><button class="btn btn-danger">Reject</button></form><?php else: ?>-<?php endif; ?></td></tr><?php endforeach; if(!$incoming): ?><tr><td colspan="7" class="muted">Belum ada request masuk.</td></tr><?php endif; ?></table></div>
<div class="card"><h3>Request Keluar</h3><table class="table"><tr><th>Waktu</th><th>Tujuan</th><th>URL</th><th>Scope</th><th>Status</th><th>Aksi</th></tr><?php foreach($outgoing as $r): ?><tr><td><?php echo e($r['created_at']); ?></td><td><?php echo e($r['target_name']); ?></td><td><?php echo e($r['target_base_url']); ?></td><td><?php echo e($r['requested_scope']); ?></td><td><?php echo status_badge($r['status']); ?></td><td><form method="post" action="api_pairing_action.php"><input type="hidden" name="csrf" value="<?php echo e(csrf_token()); ?>"><input type="hidden" name="act" value="check_status"><input type="hidden" name="id" value="<?php echo (int)$r['id']; ?>"><button class="btn btn-light">Cek Status</button></form></td></tr><?php endforeach; if(!$outgoing): ?><tr><td colspan="6" class="muted">Belum ada request keluar.</td></tr><?php endif; ?></table></div>
<div class="card"><h3>Koneksi Aktif</h3><table class="table"><tr><th>Nama</th><th>Jenis</th><th>URL Remote</th><th>Scope</th><th>Status</th><th>Test</th></tr><?php foreach($conns as $c): ?><tr><td><?php echo e($c['connection_name']); ?></td><td><?php echo e($c['connection_type']); ?></td><td><?php echo e($c['remote_base_url']); ?></td><td><?php echo e($c['access_scope']); ?></td><td><?php echo status_badge($c['status']); ?><br><small><?php echo e($c['last_test_message']??''); ?></small></td><td><?php echo legacy_api_test_buttons($c); ?></td></tr><?php endforeach; if(!$conns): ?><tr><td colspan="6" class="muted">Belum ada koneksi aktif.</td></tr><?php endif; ?></table></div>
</div></div></div><script defer src="../assets/app.js"></script></body></html>
