<?php
/* Included by admin/index.php. Uses its authenticated context, helpers, $u and $page. */
function dapur_fin_uuid(): string { $d=random_bytes(16);$d[6]=chr((ord($d[6])&15)|64);$d[8]=chr((ord($d[8])&63)|128);return vsprintf('%s%s-%s-%s-%s-%s%s%s',str_split(bin2hex($d),4)); }
function dapur_fin_ready(): bool { return table_exists('expense_categories')&&table_exists('expenses')&&table_exists('payment_requests'); }
function dapur_fin_status(string $s): string { return match($s){'draft'=>'Draft','submitted'=>'Diajukan','approved'=>'Disetujui','paid'=>'Dibayar','rejected'=>'Ditolak','cancelled'=>'Dibatalkan',default=>$s}; }
function dapur_fin_outbox(string $type,string $id,string $op,array $payload,int $ver=1): void { if(!table_exists('sync_outbox'))return;try{execq('INSERT INTO sync_outbox(event_uuid,entity_type,entity_id,operation,entity_version,payload_json) VALUES(?,?,?,?,?,?)',[dapur_fin_uuid(),$type,$id,$op,$ver,json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);}catch(Throwable $e){} }
function dapur_fin_audit(string $type,int $id,string $action,array $payload,int $uid): void { if(!table_exists('finance_audit_logs'))return;try{execq('INSERT INTO finance_audit_logs(entity_type,entity_id,action_key,payload_json,acted_by) VALUES(?,?,?,?,?)',[$type,$id,$action,json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$uid]);}catch(Throwable $e){} }

if(!dapur_fin_ready()){
 h2($page==='expenses'?'Pengeluaran':($page==='payment_requests'?'Permintaan Pembayaran':'Setting Pengeluaran'));
 echo '<div class="notice err">Import <b>db/20260711_001_finance_sync.sql</b> melalui phpMyAdmin terlebih dahulu.</div>';
 return;
}
$uid=(int)($u['id']??0);
if($page==='expenses'){
 if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
   $cat=one('SELECT * FROM expense_categories WHERE id=? AND is_active=1 AND deleted_at IS NULL',[(int)($_POST['category_id']??0)]);if(!$cat)throw new Exception('Jenis pengeluaran wajib dipilih.');
   $title=postval('title');$amount=(float)postval('amount','0');$status=postval('status','paid');if(!in_array($status,['draft','submitted','approved','paid'],true))$status='paid';if($title===''||$amount<=0)throw new Exception('Uraian dan nominal wajib diisi.');if(($cat['category_code']??'')==='OTHER'&&postval('description')==='')throw new Exception('Kategori Lain-lain memerlukan uraian rinci.');
   $no='DEXP-'.date('Ymd-His').'-'.random_int(100,999);$now=date('Y-m-d H:i:s');
   execq('INSERT INTO expenses(record_uuid,expense_no,expense_date,category_id,category_name_snapshot,title,description,amount,vendor_name,payment_method,reference_no,evidence_reference,status,due_date,approved_by,approved_at,paid_by,paid_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[dapur_fin_uuid(),$no,postval('expense_date',date('Y-m-d')),(int)$cat['id'],$cat['category_name'],$title,postval('description'),$amount,postval('vendor_name'),postval('payment_method'),postval('reference_no'),postval('evidence_reference'),$status,postval('due_date')?:null,in_array($status,['approved','paid'],true)?$uid:null,in_array($status,['approved','paid'],true)?$now:null,$status==='paid'?$uid:null,$status==='paid'?$now:null,$uid]);
   $id=(int)db()->lastInsertId();dapur_fin_audit('expense',$id,'created',['amount'=>$amount,'status'=>$status],$uid);dapur_fin_outbox('expense',(string)$id,'created',['expense_no'=>$no,'amount'=>$amount,'status'=>$status]);flash('Pengeluaran disimpan.');
  }catch(Throwable $e){flash('Gagal menyimpan pengeluaran: '.$e->getMessage(),'err');}
  redirect('?page=expenses');
 }
 h2('Pengeluaran Dapur');$cats=all('SELECT * FROM expense_categories WHERE is_active=1 AND deleted_at IS NULL ORDER BY sort_order,category_name');
 echo '<p class="muted">Biaya nonstok seperti listrik, air, gas, perawatan mesin, kendaraan, kebersihan, dan biaya operasional lain.</p><form method="post">'.csrf_field().'<div class="form-grid"><p><label>Tanggal<input type="date" name="expense_date" value="'.date('Y-m-d').'" required></label></p><p><label>Jenis<select name="category_id" required><option value="">- pilih -</option>';foreach($cats as $c)echo '<option value="'.(int)$c['id'].'">'.e($c['category_name']).'</option>';echo '</select></label></p><p><label>Uraian<input name="title" required></label></p><p><label>Nominal<input type="number" step="0.01" min="0" name="amount" required></label></p><p><label>Vendor/Penerima<input name="vendor_name"></label></p><p><label>Metode Bayar<input name="payment_method"></label></p><p><label>No Referensi<input name="reference_no"></label></p><p><label>Referensi Bukti<input name="evidence_reference"></label></p><p><label>Jatuh Tempo<input type="date" name="due_date"></label></p><p><label>Status<select name="status"><option value="paid">Dibayar</option><option value="approved">Disetujui</option><option value="submitted">Diajukan</option><option value="draft">Draft</option></select></label></p></div><p><label>Uraian Rinci<textarea name="description"></textarea></label></p><p><button class="btn">Simpan Pengeluaran</button></p></form>';
 echo '<h3>Riwayat</h3><table><tr><th>No/Tanggal</th><th>Jenis</th><th>Uraian</th><th>Nominal</th><th>Status</th></tr>';foreach(all('SELECT * FROM expenses WHERE deleted_at IS NULL ORDER BY id DESC LIMIT 100') as $r)echo '<tr><td>'.e($r['expense_no']).'<br><small>'.e($r['expense_date']).'</small></td><td>'.e($r['category_name_snapshot']).'</td><td><b>'.e($r['title']).'</b><br><small>'.e($r['description']).'</small></td><td>'.rupiah($r['amount']).'</td><td>'.e(dapur_fin_status($r['status'])).'</td></tr>';echo '</table>';
 return;
}

if($page==='payment_requests'){
 if($_SERVER['REQUEST_METHOD']==='POST'){
  $act=$_POST['act']??'create';
  try{
   if($act==='create'){
    $cat=one('SELECT * FROM expense_categories WHERE id=? AND is_active=1 AND deleted_at IS NULL',[(int)($_POST['category_id']??0)]);if(!$cat)throw new Exception('Jenis pengeluaran wajib dipilih.');$title=postval('title');$amount=(float)postval('amount','0');if($title===''||$amount<=0)throw new Exception('Judul dan nominal wajib diisi.');if(($cat['category_code']??'')==='OTHER'&&postval('description')==='')throw new Exception('Kategori Lain-lain memerlukan uraian rinci.');$no='DPAY-'.date('Ymd-His').'-'.random_int(100,999);
    execq("INSERT INTO payment_requests(record_uuid,request_no,request_date,category_id,category_name_snapshot,title,description,amount,vendor_name,due_date,reference_no,evidence_reference,status,requested_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,'submitted',?)",[dapur_fin_uuid(),$no,postval('request_date',date('Y-m-d')),(int)$cat['id'],$cat['category_name'],$title,postval('description'),$amount,postval('vendor_name'),postval('due_date')?:null,postval('reference_no'),postval('evidence_reference'),$uid]);$id=(int)db()->lastInsertId();dapur_fin_audit('payment_request',$id,'submitted',['amount'=>$amount],$uid);dapur_fin_outbox('payment_request',(string)$id,'created',['request_no'=>$no,'amount'=>$amount,'status'=>'submitted']);flash('Permintaan pembayaran diajukan.');
   }else{
    $id=(int)($_POST['id']??0);$new=postval('new_status');if(!in_array($new,['approved','paid','rejected','cancelled'],true))throw new Exception('Status tidak valid.');db()->beginTransaction();$r=one('SELECT * FROM payment_requests WHERE id=? FOR UPDATE',[$id]);if(!$r)throw new Exception('Permintaan tidak ditemukan.');$linked=(int)($r['linked_expense_id']??0);$now=date('Y-m-d H:i:s');
    if($new==='paid'&&$linked<=0){$eno='DEXP-'.date('Ymd-His').'-'.random_int(100,999);execq("INSERT INTO expenses(record_uuid,expense_no,expense_date,category_id,category_name_snapshot,title,description,amount,vendor_name,reference_no,evidence_reference,status,approved_by,approved_at,paid_by,paid_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,'paid',?,?,?,?,?)",[dapur_fin_uuid(),$eno,date('Y-m-d'),$r['category_id'],$r['category_name_snapshot'],$r['title'],$r['description'],$r['amount'],$r['vendor_name'],$r['reference_no'],$r['evidence_reference'],$uid,$now,$uid,$now,$uid]);$linked=(int)db()->lastInsertId();}
    execq("UPDATE payment_requests SET status=?,approved_by=IF(? IN ('approved','paid'),?,approved_by),approved_at=IF(? IN ('approved','paid'),?,approved_at),paid_by=IF(?='paid',?,paid_by),paid_at=IF(?='paid',?,paid_at),linked_expense_id=IF(? > 0,?,linked_expense_id),rejection_reason=?,version_no=version_no+1,updated_at=NOW() WHERE id=?",[$new,$new,$uid,$new,$now,$new,$uid,$new,$now,$linked,$linked,postval('reason'),$id]);dapur_fin_audit('payment_request',$id,'status_'.$new,['old_status'=>$r['status'],'new_status'=>$new],$uid);dapur_fin_outbox('payment_request',(string)$id,'updated',['status'=>$new,'linked_expense_id'=>$linked],(int)$r['version_no']+1);db()->commit();flash('Status permintaan diperbarui.');
   }
  }catch(Throwable $e){if(db()->inTransaction())db()->rollBack();flash('Aksi gagal: '.$e->getMessage(),'err');}
  redirect('?page=payment_requests');
 }
 h2('Permintaan Pembayaran Dapur');$cats=all('SELECT * FROM expense_categories WHERE is_active=1 AND deleted_at IS NULL ORDER BY sort_order,category_name');echo '<form method="post">'.csrf_field().'<input type="hidden" name="act" value="create"><div class="form-grid"><p><label>Tanggal<input type="date" name="request_date" value="'.date('Y-m-d').'" required></label></p><p><label>Jenis<select name="category_id" required><option value="">- pilih -</option>';foreach($cats as $c)echo '<option value="'.(int)$c['id'].'">'.e($c['category_name']).'</option>';echo '</select></label></p><p><label>Judul Tagihan<input name="title" required></label></p><p><label>Nominal<input type="number" step="0.01" min="0" name="amount" required></label></p><p><label>Vendor<input name="vendor_name"></label></p><p><label>Jatuh Tempo<input type="date" name="due_date"></label></p><p><label>No Referensi<input name="reference_no"></label></p><p><label>Referensi Bukti<input name="evidence_reference"></label></p></div><p><label>Uraian<textarea name="description"></textarea></label></p><p><button class="btn">Ajukan Pembayaran</button></p></form>';
 echo '<h3>Daftar Permintaan</h3><table><tr><th>No</th><th>Tagihan</th><th>Nominal</th><th>Jatuh Tempo</th><th>Status</th><th>Aksi</th></tr>';foreach(all('SELECT * FROM payment_requests WHERE deleted_at IS NULL ORDER BY id DESC LIMIT 100') as $r){echo '<tr><td>'.e($r['request_no']).'<br><small>'.e($r['request_date']).'</small></td><td><b>'.e($r['title']).'</b><br><small>'.e($r['category_name_snapshot'].' · '.$r['vendor_name']).'</small></td><td>'.rupiah($r['amount']).'</td><td>'.e($r['due_date']?:'-').'</td><td>'.e(dapur_fin_status($r['status'])).'</td><td>';if(!in_array($r['status'],['paid','rejected','cancelled'],true))echo '<form method="post" class="actions">'.csrf_field().'<input type="hidden" name="act" value="status"><input type="hidden" name="id" value="'.(int)$r['id'].'"><button class="btn light" name="new_status" value="approved">Setujui</button><button class="btn" name="new_status" value="paid">Dibayar</button><button class="btn danger" name="new_status" value="rejected">Tolak</button></form>';else echo '-';echo '</td></tr>';}echo '</table>';
 return;
}

if($page==='expense_categories'){
 if($_SERVER['REQUEST_METHOD']==='POST'){
  $act=$_POST['act']??'save';
  try{
   if($act==='save'){$id=(int)($_POST['id']??0);$code=strtoupper(postval('category_code'));if($code==='')$code='CUSTOM-'.date('YmdHis');if(postval('category_name')==='')throw new Exception('Nama jenis wajib diisi.');$params=[$code,postval('category_name'),postval('group_name'),postval('description'),isset($_POST['requires_approval'])?1:0,isset($_POST['requires_evidence'])?1:0,(int)postval('sort_order','0')];if($id>0){$params[]=$id;execq('UPDATE expense_categories SET category_code=?,category_name=?,group_name=?,description=?,requires_approval=?,requires_evidence=?,sort_order=?,updated_at=NOW() WHERE id=?',$params);}else{execq('INSERT INTO expense_categories(record_uuid,category_code,category_name,group_name,description,requires_approval,requires_evidence,sort_order,is_active,created_by) VALUES(?,?,?,?,?,?,?,?,1,?)',array_merge([dapur_fin_uuid()],$params,[$uid]));}flash('Jenis pengeluaran disimpan.');}
   else{$id=(int)($_POST['id']??0);$active=(int)($_POST['active']??0)===1?1:0;execq('UPDATE expense_categories SET is_active=?,updated_at=NOW() WHERE id=?',[$active,$id]);flash('Status jenis diperbarui.');}
  }catch(Throwable $e){flash('Gagal: '.$e->getMessage(),'err');}
  redirect('?page=expense_categories');
 }
 $edit=(int)($_GET['edit']??0)>0?one('SELECT * FROM expense_categories WHERE id=?',[(int)$_GET['edit']]):null;h2('Setting Jenis Pengeluaran');echo '<p class="muted">Kategori tetap menjaga rekap rapi; uraian transaksi tetap bebas.</p><form method="post">'.csrf_field().'<input type="hidden" name="act" value="save"><input type="hidden" name="id" value="'.(int)($edit['id']??0).'"><div class="form-grid"><p><label>Kode<input name="category_code" value="'.e($edit['category_code']??'').'"></label></p><p><label>Nama Jenis<input name="category_name" value="'.e($edit['category_name']??'').'" required></label></p><p><label>Kelompok<input name="group_name" value="'.e($edit['group_name']??'').'"></label></p><p><label>Urutan<input type="number" name="sort_order" value="'.e($edit['sort_order']??0).'"></label></p></div><p><label>Deskripsi<textarea name="description">'.e($edit['description']??'').'</textarea></label></p><p><label><input type="checkbox" name="requires_approval" '.(!empty($edit['requires_approval'])?'checked':'').'> Memerlukan approval</label> <label><input type="checkbox" name="requires_evidence" '.(!empty($edit['requires_evidence'])?'checked':'').'> Memerlukan bukti</label></p><p><button class="btn">Simpan</button></p></form><table><tr><th>Kode</th><th>Jenis</th><th>Kelompok</th><th>Status</th><th>Aksi</th></tr>';foreach(all('SELECT * FROM expense_categories WHERE deleted_at IS NULL ORDER BY is_active DESC,sort_order,category_name') as $r)echo '<tr><td>'.e($r['category_code']).'</td><td>'.e($r['category_name']).'</td><td>'.e($r['group_name']).'</td><td>'.($r['is_active']?'Aktif':'Nonaktif').'</td><td><div class="actions"><a class="btn light" href="?page=expense_categories&edit='.(int)$r['id'].'">Edit</a><form method="post">'.csrf_field().'<input type="hidden" name="act" value="toggle"><input type="hidden" name="id" value="'.(int)$r['id'].'"><input type="hidden" name="active" value="'.($r['is_active']?0:1).'"><button class="btn '.($r['is_active']?'danger':'light').'">'.($r['is_active']?'Nonaktifkan':'Aktifkan').'</button></form></div></td></tr>';echo '</table>';
}
