<?php
require_once __DIR__.'/../core/auth.php'; require_login(); verify_csrf();
$u=current_user(); $page=$_GET['page']??'dashboard';
$menus=[
 'dashboard'=>['Dashboard','🏠','dashboard'], 'stores'=>['Toko & API','🔌','stores'], 'finished'=>['Produk Jadi','📦','products'], 'finished_hidden'=>['Hide Produk','↳','products'], 'raw'=>['Bahan Baku','🥣','raw_materials'], 'purchases'=>['Pembelian','🛒','purchases'], 'bom'=>['BOM','🧾','bom'], 'production'=>['Produksi','🏭','production'], 'stock'=>['Stok','📊','stock'], 'sales'=>['Penjualan ke Toko','🚚','sales_distribution'], 'activities'=>['Kegiatan Pegawai','⭐','activities'], 'remuneration'=>['Remunerasi','💰','remuneration'], 'users'=>['User & Role','👤','users'], 'owner_permissions'=>['Pengaturan Permission','🛡️','permissions','owner'], 'api'=>['API Token','🔐','api']
];
if(!isset($menus[$page])) $page='dashboard'; require_perm($menus[$page][2]); if(($menus[$page][3]??'')==='owner' && !is_owner()){ http_response_code(403); die('Akses ditolak.'); }
function h2($t){echo '<h2>'.e($t).'</h2>';}
function next_no($prefix,$table,$field){return $prefix.'-'.date('Ymd').'-'.str_pad((string)(((int)(db()->query("SELECT COUNT(*) FROM $table")->fetchColumn()))+1),4,'0',STR_PAD_LEFT);} 
function postval($k,$d=''){return trim((string)($_POST[$k]??$d));}
function role_key(): string { $u=current_user(); return (string)($u['role_key']??''); }
function can_manage_finished_delete(): bool { return is_owner() || role_key()==='admin_dapur'; }
function finished_product_ref_count(int $id): int {
 $refs=0;
 $checks=[
  ['kitchen_sales_items','finished_product_id'],
  ['stock_ledger',null],
  ['production_headers','finished_product_id'],
  ['bom_headers','finished_product_id']
 ];
 foreach($checks as $c){
  if(!table_exists($c[0])) continue;
  if($c[0]==='stock_ledger') $refs+=(int)one("SELECT COUNT(*) c FROM stock_ledger WHERE item_type='finished' AND item_id=?",[$id])['c'];
  else $refs+=(int)one('SELECT COUNT(*) c FROM '.$c[0].' WHERE '.$c[1].'=?',[$id])['c'];
 }
 return $refs;
}
function call_store_api(array $store,string $path,array $payload=[],string $method='POST'){
 $url=rtrim($store['api_base_url'],'/').'/'.ltrim($path,'/'); $ch=curl_init($url); $headers=['Accept: application/json','Content-Type: application/json']; if(!empty($store['api_token'])) $headers[]='Authorization: Bearer '.$store['api_token']; curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>30,CURLOPT_CONNECTTIMEOUT=>10,CURLOPT_HTTPHEADER=>$headers,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_MAXREDIRS=>3]); if($method==='POST'){curl_setopt($ch,CURLOPT_POST,true);curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($payload,JSON_UNESCAPED_UNICODE));} $body=curl_exec($ch); $code=curl_getinfo($ch,CURLINFO_RESPONSE_CODE); $err=curl_error($ch); curl_close($ch); return [$code,$body,$err];
}
function store_api_message(int $code, string $body, string $err, string $endpoint): string{
 if($err!=='') return 'Gagal menghubungi API toko: '.$err;
 $json=json_decode(trim($body),true); $detail='';
 if(is_array($json)) $detail=(string)($json['message']??$json['error']??$json['status']??($json['ok']??''));
 if($detail==='') $detail=trim(strip_tags(substr($body,0,180)));
 if($code===401) return 'Token API toko tidak valid. Pastikan token dari menu Admin → API Dapur di toko sudah ditempel di Dapur → Toko & API. Endpoint: '.$endpoint.($detail!==''?' - '.$detail:'');
 if($code===403) return 'Token API toko aktif tetapi permission ditolak. Endpoint: '.$endpoint.($detail!==''?' - '.$detail:'');
 if($code===404) return 'Endpoint API Dapur di toko tidak ditemukan: '.$endpoint.'. Pastikan patch API Dapur di toko sudah terpasang.';
 return 'HTTP '.$code.($detail!==''?' - '.$detail:'');
}
function pick_store_products(array $json): array{
 $items=[];
 if(isset($json['products'])&&is_array($json['products'])) $items=$json['products'];
 elseif(isset($json['data'])&&is_array($json['data'])) $items=(isset($json['data']['products'])&&is_array($json['data']['products']))?$json['data']['products']:$json['data'];
 elseif((function_exists('array_is_list')?array_is_list($json):array_keys($json)===range(0,count($json)-1))) $items=$json;
 return array_values(array_filter($items,'is_array'));
}
$f=flash();
?><!doctype html><html><head><meta charset="utf-8"><title>Dapur Adena</title><link rel="stylesheet" href="../assets/app.css"><script src="../assets/app.js" defer></script></head><body><div class="app-shell"><aside class="sidebar"><div class="brand">Dapur Adena</div><div class="brand-sub">Produksi • BOM • Multi Toko</div><nav class="nav"><?php foreach($menus as $k=>$m){ if(($m[3]??'')==='owner' && !is_owner()) continue; if(can($m[2])) echo '<a class="'.($page===$k?'active':'').'" href="?page='.e($k).'"><span>'.e($m[1]).'</span> '.e($m[0]).'</a>'; } ?><a href="../logout.php">⎋ Logout</a></nav></aside><main class="main"><div class="topbar"><div><strong><?=e($menus[$page][0])?></strong><div class="muted small">Login: <?=e($u['name']??'')?></div></div></div><?php if($f): ?><div class="notice <?=e($f[1])?>"><?=e($f[0])?></div><?php endif; ?><div class="card">
<?php
if($page==='dashboard'){
 h2('Dashboard Dapur'); $stats=[['Bahan baku',db()->query('SELECT COUNT(*) FROM raw_materials')->fetchColumn()],['Produk jadi',db()->query('SELECT COUNT(*) FROM finished_products')->fetchColumn()],['Produksi',db()->query('SELECT COUNT(*) FROM production_headers')->fetchColumn()],['Penjualan ke toko',db()->query('SELECT COUNT(*) FROM kitchen_sales_headers')->fetchColumn()],['Kegiatan pegawai',db()->query('SELECT COUNT(*) FROM employee_activities')->fetchColumn()]]; echo '<div class="grid">'; foreach($stats as $s) echo '<div class="card"><div class="muted">'.e($s[0]).'</div><div class="stat">'.e($s[1]).'</div></div>'; echo '</div>';
}
elseif($page==='stores'){
 if($_SERVER['REQUEST_METHOD']==='POST'){
  $act=$_POST['act']??'';
  if($act==='save'){
   $id=(int)($_POST['id']??0);
   $params=[postval('store_code'),postval('store_name'),postval('api_base_url'),postval('api_token'),isset($_POST['is_active'])?1:0,postval('notes')];
   if($id>0){
    $params[]=$id;
    execq('UPDATE stores SET store_code=?,store_name=?,api_base_url=?,api_token=?,is_active=?,notes=? WHERE id=?',$params);
    flash('Toko/API diperbarui.');
   }else{
    execq('INSERT INTO stores(store_code,store_name,api_base_url,api_token,is_active,notes) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE store_name=VALUES(store_name),api_base_url=VALUES(api_base_url),api_token=VALUES(api_token),is_active=VALUES(is_active),notes=VALUES(notes)',$params);
    flash('Toko/API disimpan.');
   }
   redirect('?page=stores');
  }
  if($act==='delete'){
   $id=(int)($_POST['id']??0);
   $s=one('SELECT * FROM stores WHERE id=?',[$id]);
   if(!$s){ flash('Toko tidak ditemukan.','err'); redirect('?page=stores'); }
   $refs=0;
   $refs+=(int)one('SELECT COUNT(*) c FROM finished_products WHERE source_store_id=?',[$id])['c'];
   $refs+=(int)one('SELECT COUNT(*) c FROM finished_product_store_mappings WHERE store_id=?',[$id])['c'];
   $refs+=(int)one('SELECT COUNT(*) c FROM product_import_logs WHERE store_id=?',[$id])['c'];
   $refs+=(int)one('SELECT COUNT(*) c FROM kitchen_sales_headers WHERE store_id=?',[$id])['c'];
   $refs+=(int)one('SELECT COUNT(*) c FROM api_logs WHERE store_id=?',[$id])['c'];
   if($refs>0){
    execq('UPDATE stores SET is_active=0 WHERE id=?',[$id]);
    flash('Toko punya histori transaksi/import/API, jadi dihapus aman dengan status Nonaktif.');
   }else{
    execq('DELETE FROM stores WHERE id=?',[$id]);
    flash('Toko/API dihapus.');
   }
   redirect('?page=stores');
  }
  if($act==='test'){
   $s=one('SELECT * FROM stores WHERE id=?',[(int)$_POST['id']]);
   if(!$s){ flash('Toko tidak ditemukan.','err'); redirect('?page=stores'); }
   $endpoint='api/dapur/products.php';
   [$c,$b,$e]=call_store_api($s,$endpoint,[],'GET');
   $json=json_decode(trim((string)$b),true);
   if($c>=200&&$c<300&&is_array($json)){
    $items=pick_store_products($json);
    $total=(int)($json['total']??count($items));
    flash('Test API sukses. Token valid. Endpoint API Dapur aktif. Produk terbaca: '.$total.' item.','ok');
   }else{
    flash('Test API gagal. '.store_api_message((int)$c,(string)$b,(string)$e,$endpoint),'err');
   }
   redirect('?page=stores');
  }
 }
 $editId=(int)($_GET['edit']??0);
 $edit=$editId>0?one('SELECT * FROM stores WHERE id=?',[$editId]):null;
 h2('Multi Toko / Setting API');
 echo '<form method="post" class="form-grid compact-form">'.csrf_field().'<input type="hidden" name="act" value="save"><input type="hidden" name="id" value="'.(int)($edit['id']??0).'"><p><label>Kode Toko<input name="store_code" value="'.e($edit['store_code']??'').'" required></label></p><p><label>Nama Toko<input name="store_name" value="'.e($edit['store_name']??'').'" required></label></p><p><label>Base URL API Toko<input name="api_base_url" value="'.e($edit['api_base_url']??'').'" placeholder="https://toko.adena.co.id" required></label></p><p><label>Token API Toko<input name="api_token" value="'.e($edit['api_token']??'').'"></label></p><p><label>Catatan<input name="notes" value="'.e($edit['notes']??'').'"></label></p><p><label><input type="checkbox" name="is_active" '.((!$edit||!empty($edit['is_active']))?'checked':'').' style="width:auto"> Aktif</label></p><p class="actions"><button class="btn">'.($edit?'Update':'Simpan').'</button>'.($edit?' <a class="btn light" href="?page=stores">Batal</a>':'').'</p></form>';
 echo '<table><tr><th>Kode</th><th>Nama</th><th>API</th><th>Status</th><th>Aksi</th></tr>'; foreach(all('SELECT * FROM stores ORDER BY store_name') as $r){echo '<tr><td>'.e($r['store_code']).'</td><td>'.e($r['store_name']).'</td><td>'.e($r['api_base_url']).'</td><td>'.($r['is_active']?'Aktif':'Nonaktif').'</td><td><div class="actions"><form method="post">'.csrf_field().'<input type="hidden" name="act" value="test"><input type="hidden" name="id" value="'.(int)$r['id'].'"><button class="btn light">Test</button></form><a class="btn light" href="?page=stores&edit='.(int)$r['id'].'">Edit</a><form method="post" onsubmit="return confirm(\'Hapus/nonaktifkan toko ini?\')">'.csrf_field().'<input type="hidden" name="act" value="delete"><input type="hidden" name="id" value="'.(int)$r['id'].'"><button class="btn danger">Hapus</button></form></div></td></tr>'; } echo '</table>';
}
elseif($page==='raw'){
 if($_SERVER['REQUEST_METHOD']==='POST'){execq('INSERT INTO raw_materials(code,name,category,unit,min_stock,last_cost,is_active) VALUES(?,?,?,?,?,?,1) ON DUPLICATE KEY UPDATE name=VALUES(name),category=VALUES(category),unit=VALUES(unit),min_stock=VALUES(min_stock),last_cost=VALUES(last_cost)',[postval('code')?:null,postval('name'),postval('category'),postval('unit','pcs'),(float)postval('min_stock','0'),(float)postval('last_cost','0')]); flash('Bahan baku disimpan.'); redirect('?page=raw');}
 h2('Bahan Baku'); echo '<form method="post" class="form-grid">'.csrf_field().'<p><label>Kode<input name="code"></label></p><p><label>Nama<input name="name" required></label></p><p><label>Kategori<input name="category"></label></p><p><label>Satuan<input name="unit" value="gram"></label></p><p><label>Min Stok<input name="min_stock" type="number" step="0.0001"></label></p><p><label>Last Cost<input name="last_cost" type="number" step="0.01"></label></p><p><button class="btn">Simpan</button></p></form>'; echo '<table><tr><th>Nama</th><th>Satuan</th><th>Stok</th><th>Last cost</th></tr>'; foreach(all('SELECT * FROM raw_materials ORDER BY name') as $r) echo '<tr><td>'.e($r['name']).'</td><td>'.e($r['unit']).'</td><td>'.dec(stock_qty('raw',(int)$r['id'])).'</td><td>'.rupiah($r['last_cost']).'</td></tr>'; echo '</table>';
}
elseif($page==='finished'){
 if($_SERVER['REQUEST_METHOD']==='POST'){
  if(($_POST['act']??'')==='manual'){execq('INSERT INTO finished_products(code,sku,name,category,unit,sale_price,transfer_price,is_active) VALUES(?,?,?,?,?,?,?,1)',[postval('code'),postval('sku'),postval('name'),postval('category'),postval('unit','pack'),0,(float)postval('transfer_price','0')]); flash('Produk jadi disimpan.'); redirect('?page=finished');}
  if(($_POST['act']??'')==='update_finished'){ $id=(int)($_POST['id']??0); $existing=$id>0?one('SELECT * FROM finished_products WHERE id=?',[$id]):null; if(!$existing){flash('Produk jadi tidak ditemukan.','err');redirect('?page=finished');} execq('UPDATE finished_products SET code=?, sku=?, category=?, unit=?, transfer_price=?, is_active=?, updated_at=NOW() WHERE id=?',[postval('code'),postval('sku'),postval('category'),postval('unit','pack'),(float)postval('transfer_price','0'),isset($_POST['is_active'])?1:0,$id]); flash('Produk jadi diupdate. Nama tetap dikunci agar sama dengan toko.'); redirect('?page=finished');}
  if(($_POST['act']??'')==='delete_finished'){ if(!can_manage_finished_delete()){ http_response_code(403); die('Akses ditolak.'); } $id=(int)($_POST['id']??0); $existing=$id>0?one('SELECT * FROM finished_products WHERE id=?',[$id]):null; if(!$existing){flash('Produk jadi tidak ditemukan.','err');redirect('?page=finished');} $refs=finished_product_ref_count($id); if($refs>0){ execq('UPDATE finished_products SET is_active=0, updated_at=NOW() WHERE id=?',[$id]); if(table_exists('finished_product_store_mappings')) execq('UPDATE finished_product_store_mappings SET is_active=0 WHERE finished_product_id=?',[$id]); flash('Produk sudah memiliki histori transaksi/produksi/stok, jadi disembunyikan dari daftar.'); } else { if(table_exists('finished_product_store_mappings')) execq('DELETE FROM finished_product_store_mappings WHERE finished_product_id=?',[$id]); execq('DELETE FROM finished_products WHERE id=?',[$id]); flash('Produk jadi dihapus permanen.'); } redirect('?page=finished'); }
  if(($_POST['act']??'')==='import'){ $store=one('SELECT * FROM stores WHERE id=?',[(int)$_POST['store_id']]); [$c,$body,$err]=call_store_api($store,'api/dapur/products.php',[],'GET'); if($err!==''||$c<200||$c>=300){flash('Import produk gagal. '.store_api_message((int)$c,(string)$body,(string)$err,'api/dapur/products.php'),'err'); redirect('?page=finished');} $json=json_decode((string)$body,true); $items=is_array($json)?pick_store_products($json):[]; $n=0; foreach($items as $it){ if(!is_array($it))continue; $pid=(string)($it['id']??$it['product_id']??''); $name=(string)($it['name']??$it['product_name']??''); if($pid===''||$name==='')continue; execq('INSERT INTO finished_products(code,sku,name,category,unit,sale_price,transfer_price,image_path,source_store_id,source_product_id,source_payload_json,is_active,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE code=VALUES(code),sku=VALUES(sku),name=VALUES(name),category=VALUES(category),unit=VALUES(unit),image_path=VALUES(image_path),source_payload_json=VALUES(source_payload_json),updated_at=NOW()',[(string)($it['code']??$it['sku']??''),(string)($it['sku']??''),$name,(string)($it['category']??''),(string)($it['base_unit']??$it['unit']??'pack'),0,0,(string)($it['image_path']??''),(int)$store['id'],$pid,json_encode($it,JSON_UNESCAPED_UNICODE),1]); $fp=(int)db()->lastInsertId(); if($fp===0){$fp=(int)one('SELECT id FROM finished_products WHERE source_store_id=? AND source_product_id=?',[(int)$store['id'],$pid])['id'];} execq('INSERT INTO finished_product_store_mappings(finished_product_id,store_id,store_product_id,store_sku,store_product_name,store_price,is_active) VALUES(?,?,?,?,?,?,1) ON DUPLICATE KEY UPDATE store_product_id=VALUES(store_product_id),store_sku=VALUES(store_sku),store_product_name=VALUES(store_product_name),is_active=1',[$fp,(int)$store['id'],$pid,(string)($it['sku']??''),$name,0]); $n++; } execq('INSERT INTO product_import_logs(store_id,total_imported,message,created_by) VALUES(?,?,?,?)',[(int)$store['id'],$n,'Import via API', (int)($u['id']??0)]); flash('Import produk selesai: '.$n.' item.'); redirect('?page=finished'); }
 }
 h2('Produk Jadi / Finished Product');
 $activeStores=all('SELECT * FROM stores WHERE is_active=1 ORDER BY store_name');
 $finishedRows=all('SELECT fp.*, s.store_name FROM finished_products fp LEFT JOIN stores s ON s.id=fp.source_store_id WHERE fp.is_active=1 ORDER BY fp.name');
 echo '<div class="finished-toolbar card"><div class="finished-filter-grid"><p class="finished-search-field"><label>Search<input type="search" data-finished-search placeholder="Cari produk / SKU / sumber..."></label></p><p><label>Sumber<select data-finished-source><option value="">Semua sumber</option><option value="manual">Manual</option>'; foreach($activeStores as $s) echo '<option value="store:'.(int)$s['id'].'">'.e($s['store_name']).'</option>'; echo '</select></label></p><p><label>Status stok<select data-finished-stock><option value="">Semua stok</option><option value="available">Stok tersedia</option><option value="empty">Stok kosong</option></select></label></p><div class="finished-toolbar-actions"><button class="btn light" type="button" data-finished-filter-reset>Reset</button><button class="btn secondary" type="button" data-finished-import-open'.(count($activeStores)<1?' disabled':'').'>Impor Produk</button></div></div></div>';
 echo '<div class="finished-table-wrap"><table class="finished-products-table" data-finished-table><thead><tr><th class="col-product">Produk</th><th class="col-sku">SKU</th><th class="col-price">Harga Jual Dapur</th><th class="col-stock">Stok Dapur</th><th class="col-source">Sumber</th><th class="col-action">Aksi</th></tr></thead><tbody>'; foreach($finishedRows as $r){ $stock=(float)stock_qty('finished',(int)$r['id']); $sourceLabel=(string)($r['store_name']??'Manual'); $sourceKey=!empty($r['source_store_id'])?'store:'.(int)$r['source_store_id']:'manual'; $isActive=!empty($r['is_active'])?'1':'0'; $searchText=trim(($r['name']??'').' '.($r['sku']??'').' '.($r['code']??'').' '.($r['category']??'').' '.($r['unit']??'').' '.$sourceLabel.' '.rupiah($r['transfer_price']).' '.dec($stock)); echo '<tr data-finished-row data-search="'.e(strtolower($searchText)).'" data-source="'.e($sourceKey).'" data-stock="'.($stock>0?'available':'empty').'" data-active="'.$isActive.'"><td class="product-name-cell">'.e($r['name']).'</td><td>'.e($r['sku']).'</td><td>'.rupiah($r['transfer_price']).'</td><td>'.dec($stock).'</td><td>'.e($sourceLabel).'</td><td><div class="actions"><button type="button" class="btn light" data-finished-edit data-id="'.(int)$r['id'].'" data-code="'.e($r['code']??'').'" data-sku="'.e($r['sku']??'').'" data-name="'.e($r['name']??'').'" data-category="'.e($r['category']??'').'" data-unit="'.e($r['unit']??'pack').'" data-transfer-price="'.e((string)($r['transfer_price']??'0')).'" data-active="'.$isActive.'">Edit</button>'.(can_manage_finished_delete()?'<form method="post" onsubmit="return confirm(\'Hapus produk ini? Bila sudah ada histori, produk akan di-hide dari daftar.\')">'.csrf_field().'<input type="hidden" name="act" value="delete_finished"><input type="hidden" name="id" value="'.(int)$r['id'].'"><button class="btn danger">Hapus</button></form>':'').'</div></td></tr>'; } echo '<tr data-finished-empty hidden><td colspan="6" class="muted">Tidak ada produk yang sesuai filter.</td></tr></tbody></table></div>';
 echo '<div class="modal-backdrop" data-finished-import-modal hidden><div class="modal-card finished-import-modal" role="dialog" aria-modal="true" aria-labelledby="finished-import-title"><div class="modal-head"><div><h3 id="finished-import-title">Impor Produk</h3><div class="muted small">Ambil produk dari toko terhubung. Harga jual toko tidak diimpor.</div></div><button type="button" class="modal-close" data-finished-import-close aria-label="Tutup">&times;</button></div><form method="post" class="finished-import-form product-import-form" data-product-import="1" data-import-url="import_products_ajax.php">'.csrf_field().'<input type="hidden" name="act" value="import"><p><label>Toko<select name="store_id" required>'; if(count($activeStores)<1){ echo '<option value="">Belum ada toko aktif</option>'; } foreach($activeStores as $s) echo '<option value="'.(int)$s['id'].'">'.e($s['store_name']).'</option>'; echo '</select></label></p><div class="import-progress" id="product-import-progress" hidden><div class="import-progress-top"><strong>Status import</strong><span data-import-percent>0%</span></div><div class="import-progress-track"><div class="import-progress-bar" data-import-bar></div></div><div class="muted small" data-import-status>Menunggu proses import...</div></div><div class="modal-actions"><button class="btn secondary" type="submit"'.(count($activeStores)<1?' disabled':'').'>Impor Produk</button><button class="btn light" type="button" data-finished-import-close>Batal</button></div></form></div></div>';
 echo '<div class="modal-backdrop" data-finished-modal hidden><div class="modal-card finished-edit-modal" role="dialog" aria-modal="true" aria-labelledby="finished-edit-title"><div class="modal-head"><div><h3 id="finished-edit-title">Edit Produk Jadi</h3><div class="muted small">Nama produk dikunci agar tetap sama dengan toko.</div></div><button type="button" class="modal-close" data-finished-modal-close aria-label="Tutup">&times;</button></div><form method="post" class="finished-edit-grid">'.csrf_field().'<input type="hidden" name="act" value="update_finished"><input type="hidden" name="id" data-finished-field="id"><p class="field-wide"><label>Nama<input name="name" data-finished-field="name" readonly></label></p><p><label>Kode<input name="code" data-finished-field="code"></label></p><p><label>SKU<input name="sku" data-finished-field="sku"></label></p><p><label>Kategori<input name="category" data-finished-field="category"></label></p><p><label>Satuan<input name="unit" data-finished-field="unit"></label></p><p class="field-wide"><label>Harga Jual Dapur / Harga Pembelian Toko<input name="transfer_price" type="number" step="0.01" data-finished-field="transfer_price"></label><span class="muted">Dipakai sebagai harga pembelian/cost di toko saat transfer stok.</span></p><p class="finished-active-field"><label><input type="checkbox" name="is_active" data-finished-field="is_active"> Aktif</label></p><div class="modal-actions field-wide"><button class="btn" type="submit">Update</button><button class="btn light" type="button" data-finished-modal-close>Batal</button></div></form></div></div>';
}

elseif($page==='finished_hidden'){
 if($_SERVER['REQUEST_METHOD']==='POST'){
  if(($_POST['act']??'')==='restore_finished'){ if(!can_manage_finished_delete()){ http_response_code(403); die('Akses ditolak.'); } $id=(int)($_POST['id']??0); $existing=$id>0?one('SELECT * FROM finished_products WHERE id=?',[$id]):null; if(!$existing){flash('Produk jadi tidak ditemukan.','err');redirect('?page=finished_hidden');} execq('UPDATE finished_products SET is_active=1, updated_at=NOW() WHERE id=?',[$id]); if(table_exists('finished_product_store_mappings')) execq('UPDATE finished_product_store_mappings SET is_active=1 WHERE finished_product_id=?',[$id]); flash('Produk dikembalikan ke daftar Produk Jadi.'); redirect('?page=finished_hidden'); }
 }
 h2('Hide Produk Jadi');
 echo '<p class="muted">Produk di halaman ini disembunyikan dari daftar utama, tetapi histori transaksi/produksi tetap aman.</p>';
 echo '<table><tr><th>Produk</th><th>SKU</th><th>Harga Jual Dapur</th><th>Sumber</th><th>Aksi</th></tr>';
 foreach(all('SELECT fp.*, s.store_name FROM finished_products fp LEFT JOIN stores s ON s.id=fp.source_store_id WHERE fp.is_active=0 ORDER BY fp.name') as $r){ echo '<tr><td>'.e($r['name']).'</td><td>'.e($r['sku']).'</td><td>'.rupiah($r['transfer_price']).'</td><td>'.e($r['store_name']??'Manual').'</td><td>'.(can_manage_finished_delete()?'<form method="post">'.csrf_field().'<input type="hidden" name="act" value="restore_finished"><input type="hidden" name="id" value="'.(int)$r['id'].'"><button class="btn light">Aktifkan Lagi</button></form>':'-').'</td></tr>'; }
 echo '</table>';
}
elseif($page==='purchases'){
 if($_SERVER['REQUEST_METHOD']==='POST'){ $pid=0; $no=next_no('PB','purchase_headers','purchase_no'); execq('INSERT INTO purchase_headers(purchase_no,purchase_date,supplier_name,status,notes,created_by) VALUES(?,?,?,?,?,?)',[$no,postval('purchase_date',date('Y-m-d')),postval('supplier_name'),'posted',postval('notes'),(int)($u['id']??0)]); $pid=(int)db()->lastInsertId(); $total=0; foreach($_POST['raw_material_id']??[] as $i=>$rid){$rid=(int)$rid;$qty=(float)($_POST['qty'][$i]??0);$cost=(float)($_POST['unit_cost'][$i]??0); if($rid<=0||$qty<=0)continue; $rm=one('SELECT unit FROM raw_materials WHERE id=?',[$rid]); $sub=$qty*$cost; $total+=$sub; execq('INSERT INTO purchase_items(purchase_id,raw_material_id,qty,unit,unit_cost,subtotal) VALUES(?,?,?,?,?,?)',[$pid,$rid,$qty,$rm['unit']??'', $cost,$sub]); add_ledger('raw',$rid,'purchase','purchase_headers',$pid,$qty,0,$cost,$no,(int)($u['id']??0)); execq('UPDATE raw_materials SET last_cost=? WHERE id=?',[$cost,$rid]); } execq('UPDATE purchase_headers SET total_amount=?, posted_at=NOW() WHERE id=?',[$total,$pid]); flash('Pembelian diposting: '.$no); redirect('?page=purchases'); }
 h2('Pembelian Bahan Baku'); $rms=all('SELECT * FROM raw_materials WHERE is_active=1 ORDER BY name'); echo '<form method="post">'.csrf_field().'<div class="form-grid"><p><label>Tanggal<input name="purchase_date" type="date" value="'.date('Y-m-d').'" required></label></p><p><label>Supplier<input name="supplier_name"></label></p><p><label>Catatan<input name="notes"></label></p></div><table><tr><th>Bahan</th><th>Qty</th><th>Unit Cost</th></tr>'; for($i=0;$i<5;$i++){ echo '<tr><td><select name="raw_material_id[]"><option value="">-</option>'; foreach($rms as $rm) echo '<option value="'.(int)$rm['id'].'">'.e($rm['name']).'</option>'; echo '</select></td><td><input name="qty[]" type="number" step="0.0001"></td><td><input name="unit_cost[]" type="number" step="0.01"></td></tr>'; } echo '</table><p><button class="btn">Posting Pembelian</button></p></form>';
 echo '<h3>Riwayat</h3><table><tr><th>No</th><th>Tanggal</th><th>Supplier</th><th>Total</th></tr>'; foreach(all('SELECT * FROM purchase_headers ORDER BY id DESC LIMIT 20') as $r) echo '<tr><td>'.e($r['purchase_no']).'</td><td>'.e($r['purchase_date']).'</td><td>'.e($r['supplier_name']).'</td><td>'.rupiah($r['total_amount']).'</td></tr>'; echo '</table>';
}
elseif($page==='bom'){
 if($_SERVER['REQUEST_METHOD']==='POST'){ execq('INSERT INTO bom_headers(bom_code,finished_product_id,yield_qty,notes,is_active) VALUES(?,?,?,?,1)',[postval('bom_code')?:next_no('BOM','bom_headers','bom_code'),(int)$_POST['finished_product_id'],(float)postval('yield_qty','1'),postval('notes')]); $bid=(int)db()->lastInsertId(); foreach($_POST['raw_material_id']??[] as $i=>$rid){$rid=(int)$rid;$qty=(float)($_POST['qty'][$i]??0); if($rid<=0||$qty<=0)continue; $rm=one('SELECT unit FROM raw_materials WHERE id=?',[$rid]); execq('INSERT INTO bom_items(bom_id,raw_material_id,qty,unit) VALUES(?,?,?,?)',[$bid,$rid,$qty,$rm['unit']??'']); } flash('BOM dibuat.'); redirect('?page=bom'); }
 h2('BOM Backward Produk Jadi'); $fps=all('SELECT * FROM finished_products WHERE is_active=1 ORDER BY name'); $rms=all('SELECT * FROM raw_materials WHERE is_active=1 ORDER BY name'); echo '<form method="post">'.csrf_field().'<div class="form-grid"><p><label>Kode BOM<input name="bom_code" placeholder="auto bila kosong"></label></p><p><label>Produk Jadi<select name="finished_product_id">'; foreach($fps as $fp) echo '<option value="'.(int)$fp['id'].'">'.e($fp['name']).'</option>'; echo '</select></label></p><p><label>Yield Qty<input name="yield_qty" type="number" step="0.0001" value="1"></label></p><p><label>Catatan<input name="notes"></label></p></div><table><tr><th>Bahan Baku</th><th>Qty kebutuhan</th></tr>'; for($i=0;$i<8;$i++){ echo '<tr><td><select name="raw_material_id[]"><option value="">-</option>'; foreach($rms as $rm) echo '<option value="'.(int)$rm['id'].'">'.e($rm['name']).'</option>'; echo '</select></td><td><input name="qty[]" type="number" step="0.0001"></td></tr>'; } echo '</table><p><button class="btn">Simpan BOM</button></p></form><h3>Daftar BOM</h3><table><tr><th>Kode</th><th>Produk</th><th>Yield</th></tr>'; foreach(all('SELECT b.*,fp.name product_name FROM bom_headers b JOIN finished_products fp ON fp.id=b.finished_product_id ORDER BY b.id DESC') as $r) echo '<tr><td>'.e($r['bom_code']).'</td><td>'.e($r['product_name']).'</td><td>'.dec($r['yield_qty']).'</td></tr>'; echo '</table>';
}
elseif($page==='production'){
 if($_SERVER['REQUEST_METHOD']==='POST'){ $bom=one('SELECT * FROM bom_headers WHERE id=?',[(int)$_POST['bom_id']]); $qty=(float)postval('qty_produced','0'); if(!$bom||$qty<=0){flash('BOM/qty tidak valid','err');redirect('?page=production');} $factor=$qty/(float)$bom['yield_qty']; foreach(all('SELECT * FROM bom_items WHERE bom_id=?',[(int)$bom['id']]) as $bi){$need=(float)$bi['qty']*$factor; if(stock_qty('raw',(int)$bi['raw_material_id'])+0.0001 < $need){flash('Stok bahan tidak cukup untuk produksi.','err');redirect('?page=production');}} $no=next_no('PRD','production_headers','production_no'); execq('INSERT INTO production_headers(production_no,production_date,bom_id,finished_product_id,qty_produced,status,notes,created_by,posted_at) VALUES(?,?,?,?,?,?,?,?,NOW())',[$no,postval('production_date',date('Y-m-d')),(int)$bom['id'],(int)$bom['finished_product_id'],$qty,'posted',postval('notes'),(int)($u['id']??0)]); $pid=(int)db()->lastInsertId(); foreach(all('SELECT bi.*, rm.last_cost FROM bom_items bi JOIN raw_materials rm ON rm.id=bi.raw_material_id WHERE bi.bom_id=?',[(int)$bom['id']]) as $bi){$used=(float)$bi['qty']*$factor; execq('INSERT INTO production_items(production_id,raw_material_id,qty_used,unit,unit_cost) VALUES(?,?,?,?,?)',[$pid,(int)$bi['raw_material_id'],$used,$bi['unit'],(float)$bi['last_cost']]); add_ledger('raw',(int)$bi['raw_material_id'],'production','production_headers',$pid,0,$used,(float)$bi['last_cost'],$no,(int)($u['id']??0));} add_ledger('finished',(int)$bom['finished_product_id'],'production','production_headers',$pid,$qty,0,null,$no,(int)($u['id']??0)); flash('Produksi diposting: '.$no); redirect('?page=production'); }
 h2('Produksi dari BOM'); echo '<form method="post" class="form-grid">'.csrf_field().'<p><label>Tanggal<input name="production_date" type="date" value="'.date('Y-m-d').'"></label></p><p><label>BOM<select name="bom_id">'; foreach(all('SELECT b.*,fp.name product_name FROM bom_headers b JOIN finished_products fp ON fp.id=b.finished_product_id WHERE b.is_active=1 ORDER BY fp.name') as $b) echo '<option value="'.(int)$b['id'].'">'.e($b['bom_code'].' - '.$b['product_name']).'</option>'; echo '</select></label></p><p><label>Qty Produksi<input name="qty_produced" type="number" step="0.0001" required></label></p><p><label>Catatan<input name="notes"></label></p><p><button class="btn">Posting Produksi</button></p></form>'; echo '<table><tr><th>No</th><th>Tanggal</th><th>Produk</th><th>Qty</th></tr>'; foreach(all('SELECT p.*,fp.name product_name FROM production_headers p JOIN finished_products fp ON fp.id=p.finished_product_id ORDER BY p.id DESC LIMIT 30') as $r) echo '<tr><td>'.e($r['production_no']).'</td><td>'.e($r['production_date']).'</td><td>'.e($r['product_name']).'</td><td>'.dec($r['qty_produced']).'</td></tr>'; echo '</table>';
}
elseif($page==='stock'){
 h2('Stok Dapur'); echo '<h3>Bahan Baku</h3><table><tr><th>Nama</th><th>Stok</th><th>Satuan</th></tr>'; foreach(all('SELECT * FROM raw_materials ORDER BY name') as $r) echo '<tr><td>'.e($r['name']).'</td><td>'.dec(stock_qty('raw',(int)$r['id'])).'</td><td>'.e($r['unit']).'</td></tr>'; echo '</table><h3>Barang Jadi</h3><table><tr><th>Nama</th><th>Stok</th><th>Satuan</th></tr>'; foreach(all('SELECT * FROM finished_products ORDER BY name') as $r) echo '<tr><td>'.e($r['name']).'</td><td>'.dec(stock_qty('finished',(int)$r['id'])).'</td><td>'.e($r['unit']).'</td></tr>'; echo '</table>';
}
elseif($page==='sales'){
 if($_SERVER['REQUEST_METHOD']==='POST'){ $store=one('SELECT * FROM stores WHERE id=?',[(int)$_POST['store_id']]); $no=next_no('KDS','kitchen_sales_headers','sale_no'); execq('INSERT INTO kitchen_sales_headers(sale_no,sale_date,store_id,sale_type,status,notes,created_by,posted_at) VALUES(?,?,?,?,?,?,?,NOW())',[$no,postval('sale_date',date('Y-m-d')),(int)$store['id'],'store_distribution','posted',postval('notes'),(int)($u['id']??0)]); $sid=(int)db()->lastInsertId(); $items=[];$total=0; foreach($_POST['finished_product_id']??[] as $i=>$fid){$fid=(int)$fid;$qty=(float)($_POST['qty'][$i]??0); if($fid<=0||$qty<=0)continue; if(stock_qty('finished',$fid)+0.0001<$qty){flash('Stok barang jadi tidak cukup.','err');redirect('?page=sales');} $fp=one('SELECT * FROM finished_products WHERE id=?',[$fid]); $priceRaw=trim((string)($_POST['transfer_price'][$i]??'')); $price=$priceRaw===''?(float)$fp['transfer_price']:(float)$priceRaw; $sub=$qty*$price; $total+=$sub; execq('INSERT INTO kitchen_sales_items(sale_id,finished_product_id,qty,unit,transfer_price,subtotal) VALUES(?,?,?,?,?,?)',[$sid,$fid,$qty,$fp['unit'],$price,$sub]); add_ledger('finished',$fid,'sale_to_store','kitchen_sales_headers',$sid,0,$qty,$price,$no,(int)($u['id']??0)); $map=one('SELECT * FROM finished_product_store_mappings WHERE finished_product_id=? AND store_id=?',[$fid,(int)$store['id']]); $items[]=['store_product_id'=>$map['store_product_id']??$fp['source_product_id']??$fid,'sku'=>$map['store_sku']??$fp['sku'],'name'=>$fp['name'],'qty'=>$qty,'unit'=>$fp['unit'],'transfer_price'=>$price]; }
 execq('UPDATE kitchen_sales_headers SET total_amount=? WHERE id=?',[$total,$sid]); $payload=['store_code'=>$store['store_code'],'source'=>'DAPUR_ADENA','transfer_no'=>$no,'transfer_date'=>postval('sale_date',date('Y-m-d')),'items'=>$items,'notes'=>postval('notes')]; [$c,$b,$e]=call_store_api($store,'api/v1/kitchen/receive-transfer.php',$payload,'POST'); $status=($c>=200&&$c<300)?'sent_to_store':'failed_sync'; execq('UPDATE kitchen_sales_headers SET status=?, synced_at=NOW(), remote_response=? WHERE id=?',[$status,($e?:$b),$sid]); execq('INSERT INTO api_logs(store_id,endpoint,direction,status,message,payload_json) VALUES(?,?,?,?,?,?)',[(int)$store['id'],'receive-transfer','out',$status,($e?:'HTTP '.$c),json_encode($payload,JSON_UNESCAPED_UNICODE)]); flash('Penjualan/transfer ke toko dibuat: '.$no.' status '.$status, $status==='failed_sync'?'err':'ok'); redirect('?page=sales'); }
 h2('Penjualan / Distribusi ke Toko'); $fps=all('SELECT * FROM finished_products WHERE is_active=1 ORDER BY name'); echo '<form method="post">'.csrf_field().'<div class="form-grid"><p><label>Tanggal<input name="sale_date" type="date" value="'.date('Y-m-d').'"></label></p><p><label>Toko Tujuan<select name="store_id">'; foreach(all('SELECT * FROM stores WHERE is_active=1 ORDER BY store_name') as $s) echo '<option value="'.(int)$s['id'].'">'.e($s['store_name']).'</option>'; echo '</select></label></p><p><label>Catatan<input name="notes"></label></p></div><table><tr><th>Produk</th><th>Qty</th><th>Harga Jual Dapur</th><th>Stok</th></tr>'; for($i=0;$i<6;$i++){ echo '<tr><td><select name="finished_product_id[]"><option value="">-</option>'; foreach($fps as $fp) echo '<option value="'.(int)$fp['id'].'">'.e($fp['name']).'</option>'; echo '</select></td><td><input name="qty[]" type="number" step="0.0001"></td><td><input name="transfer_price[]" type="number" step="0.01" placeholder="otomatis dari produk"></td><td class="muted">isi sesuai stok</td></tr>'; } echo '</table><p><button class="btn">Posting & Kirim API ke Toko</button></p></form>'; echo '<table><tr><th>No</th><th>Toko</th><th>Total</th><th>Status</th></tr>'; foreach(all('SELECT h.*,s.store_name FROM kitchen_sales_headers h LEFT JOIN stores s ON s.id=h.store_id ORDER BY h.id DESC LIMIT 30') as $r) echo '<tr><td>'.e($r['sale_no']).'</td><td>'.e($r['store_name']).'</td><td>'.rupiah($r['total_amount']).'</td><td><span class="badge">'.e($r['status']).'</span></td></tr>'; echo '</table>';
}
elseif($page==='activities'){
 if($_SERVER['REQUEST_METHOD']==='POST'){ if(($_POST['act']??'')==='emp'){execq('INSERT INTO employees(employee_name,phone,is_active) VALUES(?,?,1)',[postval('employee_name'),postval('phone')]); flash('Pegawai disimpan.'); redirect('?page=activities');} if(($_POST['act']??'')==='type'){execq('INSERT INTO activity_types(activity_name,category,unit_name,point_weight,is_active) VALUES(?,?,?,?,1)',[postval('activity_name'),postval('category'),postval('unit_name','kegiatan'),(float)postval('point_weight','1')]); flash('Jenis kegiatan disimpan.'); redirect('?page=activities');} $at=one('SELECT * FROM activity_types WHERE id=?',[(int)$_POST['activity_type_id']]); $qty=(float)postval('qty','1'); $w=(float)$at['point_weight']; execq('INSERT INTO employee_activities(activity_date,employee_id,activity_type_id,qty,point_weight,total_points,notes,created_by) VALUES(?,?,?,?,?,?,?,?)',[postval('activity_date',date('Y-m-d')),(int)$_POST['employee_id'],(int)$at['id'],$qty,$w,$qty*$w,postval('notes'),(int)($u['id']??0)]); flash('Kegiatan pegawai dicatat.'); redirect('?page=activities'); }
 h2('Kegiatan Pegawai & Bobot Poin'); echo '<h3>Tambah Pegawai</h3><form method="post" class="actions">'.csrf_field().'<input type="hidden" name="act" value="emp"><input name="employee_name" placeholder="Nama pegawai" required><input name="phone" placeholder="HP"><button class="btn light">Simpan Pegawai</button></form><h3>Tambah Jenis Kegiatan</h3><form method="post" class="actions">'.csrf_field().'<input type="hidden" name="act" value="type"><input name="activity_name" placeholder="Nama kegiatan" required><input name="category" placeholder="Kategori"><input name="unit_name" placeholder="Satuan"><input name="point_weight" type="number" step="0.01" placeholder="Bobot"><button class="btn light">Simpan Kegiatan</button></form><h3>Input Kegiatan</h3><form method="post" class="form-grid">'.csrf_field().'<p><label>Tanggal<input name="activity_date" type="date" value="'.date('Y-m-d').'"></label></p><p><label>Pegawai<select name="employee_id">'; foreach(all('SELECT * FROM employees WHERE is_active=1 ORDER BY employee_name') as $emp) echo '<option value="'.(int)$emp['id'].'">'.e($emp['employee_name']).'</option>'; echo '</select></label></p><p><label>Kegiatan<select name="activity_type_id">'; foreach(all('SELECT * FROM activity_types WHERE is_active=1 ORDER BY activity_name') as $a) echo '<option value="'.(int)$a['id'].'">'.e($a['activity_name'].' ('.$a['point_weight'].')').'</option>'; echo '</select></label></p><p><label>Qty<input name="qty" type="number" step="0.0001" value="1"></label></p><p><label>Catatan<input name="notes"></label></p><p><button class="btn">Catat</button></p></form>'; echo '<table><tr><th>Tanggal</th><th>Pegawai</th><th>Kegiatan</th><th>Poin</th></tr>'; foreach(all('SELECT ea.*,e.employee_name,a.activity_name FROM employee_activities ea JOIN employees e ON e.id=ea.employee_id JOIN activity_types a ON a.id=ea.activity_type_id ORDER BY ea.id DESC LIMIT 40') as $r) echo '<tr><td>'.e($r['activity_date']).'</td><td>'.e($r['employee_name']).'</td><td>'.e($r['activity_name']).'</td><td>'.dec($r['total_points']).'</td></tr>'; echo '</table>';
}
elseif($page==='remuneration'){
 if($_SERVER['REQUEST_METHOD']==='POST'){ $name=postval('period_name');$start=postval('start_date');$end=postval('end_date');$fund=(float)postval('total_fund','0'); execq('INSERT INTO remuneration_periods(period_name,start_date,end_date,total_fund,status) VALUES(?,?,?,?,?)',[$name,$start,$end,$fund,'draft']); $pid=(int)db()->lastInsertId(); $rows=all('SELECT employee_id,SUM(total_points) pts FROM employee_activities WHERE activity_date BETWEEN ? AND ? GROUP BY employee_id',[$start,$end]); $total=array_sum(array_map(fn($r)=>(float)$r['pts'],$rows)); foreach($rows as $r){$pct=$total>0?(float)$r['pts']/$total:0; execq('INSERT INTO remuneration_items(period_id,employee_id,total_points,point_percent,amount) VALUES(?,?,?,?,?)',[$pid,(int)$r['employee_id'],(float)$r['pts'],$pct,$pct*$fund]);} flash('Perhitungan remunerasi dibuat.'); redirect('?page=remuneration'); }
 h2('Remunerasi'); echo '<form method="post" class="form-grid">'.csrf_field().'<p><label>Nama Periode<input name="period_name" value="Remun '.date('M Y').'"></label></p><p><label>Awal<input name="start_date" type="date" required></label></p><p><label>Akhir<input name="end_date" type="date" required></label></p><p><label>Total Dana<input name="total_fund" type="number"></label></p><p><button class="btn">Hitung</button></p></form>'; foreach(all('SELECT * FROM remuneration_periods ORDER BY id DESC LIMIT 10') as $p){echo '<h3>'.e($p['period_name']).' <span class="muted">'.e($p['start_date'].' s.d. '.$p['end_date']).'</span></h3><table><tr><th>Pegawai</th><th>Poin</th><th>%</th><th>Nominal</th></tr>'; foreach(all('SELECT ri.*,e.employee_name FROM remuneration_items ri JOIN employees e ON e.id=ri.employee_id WHERE period_id=? ORDER BY amount DESC',[(int)$p['id']]) as $r) echo '<tr><td>'.e($r['employee_name']).'</td><td>'.dec($r['total_points']).'</td><td>'.number_format((float)$r['point_percent']*100,2).'%</td><td>'.rupiah($r['amount']).'</td></tr>'; echo '</table>'; }
}
elseif($page==='users'){
 if($_SERVER['REQUEST_METHOD']==='POST'){ $hash=password_hash(postval('password'),PASSWORD_DEFAULT); execq('INSERT INTO users(username,name,email,password_hash,role_id,is_active) VALUES(?,?,?,?,?,1)',[postval('username'),postval('name'),postval('email'),$hash,(int)$_POST['role_id']]); flash('User dibuat.'); redirect('?page=users'); }
 h2('User & Role'); echo '<form method="post" class="form-grid">'.csrf_field().'<p><label>Username<input name="username" required></label></p><p><label>Nama<input name="name" required></label></p><p><label>Email<input name="email"></label></p><p><label>Password<input name="password" type="password" required></label></p><p><label>Role<select name="role_id">'; foreach(all('SELECT * FROM roles ORDER BY id') as $r) echo '<option value="'.(int)$r['id'].'">'.e($r['role_name']).'</option>'; echo '</select></label></p><p><button class="btn">Buat User</button></p></form><table><tr><th>Username</th><th>Nama</th><th>Role</th></tr>'; foreach(all('SELECT u.*,r.role_name FROM users u JOIN roles r ON r.id=u.role_id ORDER BY u.id') as $r) echo '<tr><td>'.e($r['username']).'</td><td>'.e($r['name']).'</td><td>'.e($r['role_name']).'</td></tr>'; echo '</table>';
}

elseif($page==='owner_permissions'){
 if(!is_owner()){ http_response_code(403); die('Akses ditolak.'); }
 if($_SERVER['REQUEST_METHOD']==='POST'){
  $roleId=(int)($_POST['role_id']??0);
  $role=$roleId>0?one('SELECT * FROM roles WHERE id=?',[$roleId]):null;
  if(!$role || in_array((string)$role['role_key'],['owner','superadmin'],true)){ flash('Role owner tidak perlu diatur permission-nya.','err'); redirect('?page=owner_permissions'); }
  execq('DELETE FROM role_permissions WHERE role_id=?',[$roleId]);
  foreach(($_POST['permission_id']??[]) as $pid){ $pid=(int)$pid; if($pid>0) execq('INSERT IGNORE INTO role_permissions(role_id,permission_id) VALUES(?,?)',[$roleId,$pid]); }
  flash('Permission role '.($role['role_name']??'').' diperbarui.'); redirect('?page=owner_permissions&role_id='.$roleId);
 }
 h2('Pengaturan User Permission');
 $roles=all("SELECT * FROM roles WHERE role_key NOT IN ('owner','superadmin') ORDER BY id");
 $roleId=(int)($_GET['role_id']??($roles[0]['id']??0));
 $selectedRole=$roleId>0?one('SELECT * FROM roles WHERE id=?',[$roleId]):null;
 if(!$selectedRole || in_array((string)$selectedRole['role_key'],['owner','superadmin'],true)){ $selectedRole=$roles[0]??null; $roleId=(int)($selectedRole['id']??0); }
 echo '<p class="muted">Owner selalu memiliki akses penuh. Permission di sini berlaku untuk role selain owner.</p>';
 echo '<form method="get" class="actions"><input type="hidden" name="page" value="owner_permissions"><label>Role <select name="role_id" onchange="this.form.submit()">'; foreach($roles as $r) echo '<option value="'.(int)$r['id'].'" '.((int)$r['id']===$roleId?'selected':'').'>'.e($r['role_name']).'</option>'; echo '</select></label><noscript><button class="btn light">Pilih</button></noscript></form>';
 if($selectedRole){
  $active=[]; foreach(all('SELECT permission_id FROM role_permissions WHERE role_id=?',[$roleId]) as $rp) $active[(int)$rp['permission_id']]=true;
  echo '<form method="post">'.csrf_field().'<input type="hidden" name="role_id" value="'.$roleId.'"><table><tr><th>Aktif</th><th>Permission</th><th>Keterangan</th></tr>';
  foreach(all('SELECT * FROM permissions ORDER BY id') as $p){ echo '<tr><td><input type="checkbox" name="permission_id[]" value="'.(int)$p['id'].'" '.(isset($active[(int)$p['id']])?'checked':'').'></td><td>'.e($p['permission_key']).'</td><td>'.e($p['permission_name']).'</td></tr>'; }
  echo '</table><p><button class="btn">Simpan Permission</button></p></form>';
 }
}
elseif($page==='api'){
 if($_SERVER['REQUEST_METHOD']==='POST'){ $plain='kd_'.bin2hex(random_bytes(24)); execq('INSERT INTO api_tokens(token_name,token_hash,permissions_json,is_active) VALUES(?,?,?,1)',[postval('token_name'),hash('sha256',$plain),json_encode(['products.view','stock.view','*'])]); flash('Token dibuat. Simpan token ini sekarang: '.$plain); redirect('?page=api'); }
 h2('API Token Dapur'); echo '<p class="muted">Token ini untuk integrasi eksternal bila diperlukan. Token toko untuk menerima kiriman dapur diatur di menu Toko & API.</p><form method="post" class="actions">'.csrf_field().'<input name="token_name" placeholder="Nama token" required><button class="btn">Generate Token</button></form><table><tr><th>Nama</th><th>Status</th><th>Terakhir Dipakai</th></tr>'; foreach(all('SELECT * FROM api_tokens ORDER BY id DESC') as $r) echo '<tr><td>'.e($r['token_name']).'</td><td>'.($r['is_active']?'Aktif':'Nonaktif').'</td><td>'.e($r['last_used_at']).'</td></tr>'; echo '</table>';
}
?></div></main></div></body></html>
